### ISSUE TITLE
Lineage-18.1 branch sepolicy not working

### ISSUE THREAD

**Issue by IntelliPerson** [fcuzzocrea/android_device_samsung_universal5420-common#6]
android 11 sepolicy not working

**Comment by MIUI56** [comment]
Hi ,stop sepolicy for now and add me your ha3g dt repo  or push commit to Gerrit

**Comment by IntelliPerson** [comment]
hello bro good to see you here, i checked the ha3g device trees you made, i added some fixes on it and i will use them to update the lineage-17.1 unofficial ha3g project to android 11 version thanks

**Comment by IntelliPerson** [comment]
I found a problem with the recent Kmsg file contexts.both universal 5420 common and Samsung sepolicy have been identified, but this error has already been resolved forgot to close the problem

**Comment by fcuzzocrea** [comment]
use the tree ad exynos5420 github organization. this is unmantained.

**Comment by MIUI56** [comment]
need to add firmare and  firmare-modem sepolicy in file__conexts

**Comment by MIUI56** [comment]
DarkCamper242 show me your dt

**Comment by IntelliPerson** [comment]
of course here is the common repository

**Comment by IntelliPerson** [comment]
https://github.com/DarkCamper242/ha3g-common-MIUI56.git
